### ISSUE TITLE
Room Loading Improvements

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#181]
# Use Case

- Powerbi wants to load Rooms and override the material with a transparent one (but only the material(s) on those rooms)

# TODO

- [ ] Implement new material shader for rooms
- [ ] Settings options
  - [ ] Add option to allow the viewer to load instances which are marked as hidden
  - [ ] Add option to hide instances marked as hidden by default
  - [ ] Add callback to override material per instance
