### ISSUE TITLE
🐘 SPIKE: g3d Decomposition

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#214]
# Notes

Advantages:
  - improved time to first presentation
  - not bound to a server (but can be used by a server)

# TODO

- [x] Instance indexing file
  - Element index mapping
  
- [x] Mesh indexing file (compressed at rest, g3d)
  - number of instances (?)
  - instance to mesh mapping (correlation to mesh file is based on a naming scheme 'mesh_0.g3d', 'mesh_1.g3d')
  - instance to element index mapping
  - mesh descriptors (num indices, num vertices, etc); serves to pre-allocate in the viewer

- [x] Mesh g3d files (compressed at rest)
  - instance transforms
  - contains material data (color, smoothness, glossiness)
  - submeshes (sorted by transparency?)
  - indices
  - vertices

- [x] Update front-end to query those files

- [x] Implement PowerBI performance tests for loading decomposed g3ds:
  - [ ] TinyHouse
  - [x] Wolford
  - [x] Skanska
  - [ ] Kahua

# LATER

- Progressive loading (heuristic TBD - possibly bounding box size)
- Entity data loaded as a single chunk
- Graceful failure in case of exceeding specific limits.
