### ISSUE TITLE
🐘 SPIKE: g3d Progressive Loading

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#216]
# WHY?

- Improve the time-to-first presentation
- Improve the perception of the loading experience:
  - Instances should appear gradually
  - The scene can be manipulated during the loading process.
  - A loading indicator in PowerBI which will not obfuscate the view.

# TODO

- [x] Implement the simplest thing that could possibly work to have instances appear as they are acquired from the storage back-end.
- [x] Implement fonctionnal mesh merging 
- [x] Implement proper opaque/transparent code path
- [x] Implement existing viewer API in merge path
- [x] Implement PBI ready API
- [x] Perform a preliminary integration in PowerBI for testing purposes
- [x] Adapt the old VIM loading pipeline into the new loading pipeline (insertable mesh)
- [x] Implement basic mesh instancing 
- [x] Implement existing viewer API in instancing path
- [ ] Test with Skanska x 5 (use vimtool to merge) in PowerBI

**Comment by mavimaec** [comment]
@mavimaec to sort out why we can't test with 5 skanskas (is something wrong with merge?)
