### ISSUE TITLE
🐍 VIM WebGL Component Update

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#219]
# TODO

- [x] Newer VIM files containing "long:Id" for the Element ID will currently cause the VIM webgl viewer to throw an error while loading. The solution is to consume the latest object model in vim-ts which looks for either "int:Id" or "long:Id" among the columns
- [x] Fix CSS arrow misalignment in project inspector
- [x] Remove extraneous console logs
- [x] Consume latest VIM webgl component in VIM Cloud

**Comment by vim-sroberge** [comment]
@mavimaec I have included your changes in this package version.

[0.2.27-dev.19](https://www.npmjs.com/package/vim-webgl-component/v/0.2.27-dev.19)
