### ISSUE TITLE
Fix jsfiddle viewer samples posted in "main" branch README

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#231]
# TODO

- [x] Print a console message prior to sending the VIM request to indicate that the widget is loading
- [x] The initial camera framing seems too far from the model
- [x] The color sample doesn't appear to be coloring any elements
- [x] Review each posted JSFiddle to validate its working state
- [x] Validate that the vim-webgl-component repo documentation + readme + samples are also up-to-date
- [x] @mavimaec to notify the following people when the **vim-webgl-component** has been updated (they have already been notified of the update to the vim-webgl-viewer).
  - [x] soheil.fathi@codainsights.com 
  - [x] filippo.trevisan@kapitolgroup.com.au , andy.wong@kapitolgroup.com.au
