### ISSUE TITLE
User can customize mouse scroll in/out sensitivity

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#234]
# Context

Users at Kapitol Group are comparing the controls between our VIM WebGL viewer and the Forge viewer. They feel the camera scroll in/out is too slow and would like to customize the speed.

Here is a comparison video they made:
https://github.com/vimaec/vim-webgl-viewer/assets/48137774/f2fc3a49-4c84-4196-aad6-6875d3052313

# TODO

- [x] Add to WebGL Viewer API a camera scroll sensitivity (1..10)
- [x] Add settings UI to WebGL component to control camera scroll sensitivity
  - Ensure this camera scroll sensitivity is persisted in localstorage by default
- [x] Get feedback from Kapitol Group on standalone component test
  - @mavimaec to signal to David Cheung when a new build can be tested
- [x] Add configuration field to PowerBI to control camera scroll sensitivity
