### ISSUE TITLE
🌶 Rosendin improvements

### ISSUE THREAD

**Issue by mavimaec** [vimaec/vim-webgl-viewer#238]
# TODO

(Start on week of May 6)

- [x] Share technical plan with Rosendin about the approach to validate that the API is what they want.
  - share it with @mavimaec 

- [x] Update vim-component with a streamlined container creation process and share a JS Fiddle with Rosendin

- [x] Implement a hook which would allows the client code to asynchronously provide a React component to render within the BIM inspector's structure
  - This way, the user can add text boxes, buttons, etc.
  - See gist draft: https://gist.github.com/vim-sroberge/d65032795f5a1a7bc84473478ddfd63f

- [ ] Fix root element CSS manipulations raised by Rosendin
